version: '3'
x-airflow-common:
  &airflow-common
  environment:
    - _PIP_ADDITIONAL_REQUIREMENTS=apache-airflow[google]==2.2.0 google-cloud-vision==2.4.2
services:
  airflow-webserver:
    environment:
      - AIRFLOW__CORE__LOAD_EXAMPLES=false

  airflow-scheduler:
    environment:
      - AIRFLOW__CORE__LOAD_EXAMPLES=false
  
  airflow-worker:
    environment:
      - AIRFLOW__CORE__LOAD_EXAMPLES=false

  custom-database:
    image: postgres:13
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: homework2
    volumes:
      - custom-db-volume:/var/lib/postgresql/data
    ports:
      - "5433:5432"

volumes:
  custom-db-volume: